# Generated by Django 3.1.6 on 2021-02-10 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='basic_license',
        ),
        migrations.AddField(
            model_name='basiclicense',
            name='beat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.beat'),
        ),
    ]
