# Generated by Django 3.1.6 on 2021-02-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210210_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='beat_thumbnails'),
        ),
    ]
