# Generated by Django 3.1.6 on 2021-02-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_beat_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='mp3_file',
            field=models.FileField(blank=True, null=True, upload_to='mp3_files'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='keywords',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
