# Generated by Django 3.1.6 on 2021-02-12 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210212_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Basic License', max_length=70)),
                ('price', models.DecimalField(decimal_places=2, default=29.9, max_digits=8)),
                ('num_distribution_copies', models.CharField(default='2000', max_length=10)),
                ('num_free_downloads', models.CharField(default='Unlimited', max_length=10)),
                ('num_audio_streams', models.CharField(default='500000', max_length=10)),
                ('num_music_videos', models.CharField(default='1', max_length=10)),
                ('num_non_monetized_video_streams', models.CharField(default='500000', max_length=10)),
                ('num_monetized_video_streams', models.CharField(default='1', max_length=10)),
                ('broadcoasting_rights', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('num_radio_stations', models.CharField(default='2', max_length=10)),
                ('allow_profit_performances', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('num_not_for_profit_performances', models.CharField(default='Unlimited', max_length=10)),
                ('beats_publishing_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('beats_hook_publishing_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('top_lines_vocals_publishing_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.beat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
