# Generated by Django 3.1.6 on 2021-02-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_premiumlicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumlicense',
            name='price',
            field=models.DecimalField(decimal_places=2, default=49.9, max_digits=8),
        ),
        migrations.AlterField(
            model_name='premiumlicense',
            name='title',
            field=models.CharField(default='Premium License', max_length=70),
        ),
    ]
