# Generated by Django 3.1.6 on 2021-02-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210213_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiclicense',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumlicense',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
