# Generated by Django 3.1.6 on 2021-02-16 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210215_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiclicense',
            name='beat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.beat'),
        ),
    ]
