# Generated by Django 3.1.6 on 2021-02-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210216_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiclicense',
            name='title',
            field=models.CharField(default='Basic License', editable='False', max_length=70),
        ),
        migrations.AlterField(
            model_name='premiumlicense',
            name='title',
            field=models.CharField(default='Premium License', editable='False', max_length=70),
        ),
    ]
