# Generated by Django 3.1.6 on 2021-02-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210216_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='beat_length',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='beat',
            name='bpm',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='beat',
            name='tone_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='basiclicense',
            name='title',
            field=models.CharField(default='Basic License', editable=False, max_length=70),
        ),
        migrations.AlterField(
            model_name='premiumlicense',
            name='title',
            field=models.CharField(default='Premium License', editable=False, max_length=70),
        ),
    ]
