# Generated by Django 3.1.6 on 2021-02-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='license_pdf',
            field=models.FileField(blank=True, null=True, upload_to='license_pdfs'),
        ),
    ]
