# Generated by Django 3.1.6 on 2021-02-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_orderitem_license_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='video',
            field=models.CharField(blank=True, help_text='Youtube embed code', max_length=100, null=True),
        ),
    ]
