# Generated by Django 3.1.6 on 2021-02-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20210226_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='video',
            field=models.CharField(blank=True, help_text='Youtube embed code', max_length=200, null=True),
        ),
    ]
