# Generated by Django 3.1.6 on 2021-02-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20210226_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='wav_file',
            field=models.FileField(blank=True, null=True, upload_to='wav_files'),
        ),
    ]
