# Generated by Django 3.1.6 on 2021-03-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_beat_wav_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
