# Generated by Django 3.1.6 on 2021-03-03 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20210301_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumlicense',
            name='num_audio_streams',
            field=models.CharField(default='1000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='premiumlicense',
            name='num_distribution_copies',
            field=models.CharField(default='10000', max_length=10),
        ),
        migrations.AlterField(
            model_name='premiumlicense',
            name='num_non_monetized_video_streams',
            field=models.CharField(default='Unlimited', max_length=10),
        ),
        migrations.CreateModel(
            name='UnlimitedLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unlimited License', editable=False, max_length=70)),
                ('price', models.DecimalField(decimal_places=2, default=199.9, max_digits=8)),
                ('num_distribution_copies', models.CharField(default='Unlimited', max_length=10)),
                ('num_free_downloads', models.CharField(default='Unlimited', max_length=10)),
                ('num_audio_streams', models.CharField(default='Unlimited', max_length=10)),
                ('num_music_videos', models.CharField(default='Unlimited', max_length=10)),
                ('num_non_monetized_video_streams', models.CharField(default='Unlimited', max_length=10)),
                ('num_monetized_video_streams', models.CharField(default='Unlimited', max_length=10)),
                ('broadcoasting_rights', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('num_radio_stations', models.CharField(default='2s', max_length=10)),
                ('allow_profit_performances', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('num_not_for_profit_performances', models.CharField(default='Unlimited', max_length=10)),
                ('beats_publishing_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('beats_hook_publishing_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('top_lines_vocals_publishing_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.beat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremiumPlusLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Premium Plus License', editable=False, max_length=70)),
                ('price', models.DecimalField(decimal_places=2, default=99.9, max_digits=8)),
                ('num_distribution_copies', models.CharField(default='100000', max_length=10)),
                ('num_free_downloads', models.CharField(default='Unlimited', max_length=10)),
                ('num_audio_streams', models.CharField(default='10000000', max_length=10)),
                ('num_music_videos', models.CharField(default='2', max_length=10)),
                ('num_non_monetized_video_streams', models.CharField(default='Unlimited', max_length=10)),
                ('num_monetized_video_streams', models.CharField(default='2', max_length=10)),
                ('broadcoasting_rights', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('num_radio_stations', models.CharField(default='2', max_length=10)),
                ('allow_profit_performances', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('num_not_for_profit_performances', models.CharField(default='Unlimited', max_length=10)),
                ('beats_publishing_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('beats_hook_publishing_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('top_lines_vocals_publishing_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.beat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExclusiveLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Exclusive License', editable=False, max_length=70)),
                ('price', models.DecimalField(decimal_places=2, default=499.9, max_digits=8)),
                ('num_distribution_copies', models.CharField(default='Unlimited', max_length=10)),
                ('num_free_downloads', models.CharField(default='Unlimited', max_length=10)),
                ('num_audio_streams', models.CharField(default='Unlimited', max_length=10)),
                ('num_music_videos', models.CharField(default='Unlimited', max_length=10)),
                ('num_non_monetized_video_streams', models.CharField(default='Unlimited', max_length=10)),
                ('num_monetized_video_streams', models.CharField(default='Unlimited', max_length=10)),
                ('broadcoasting_rights', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('num_radio_stations', models.CharField(default='2s', max_length=10)),
                ('allow_profit_performances', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('num_not_for_profit_performances', models.CharField(default='Unlimited', max_length=10)),
                ('beats_publishing_percentage', models.CharField(default=50, max_length=10)),
                ('beats_hook_publishing_percentage', models.CharField(default=35, max_length=10)),
                ('top_lines_vocals_publishing_percentage', models.CharField(default=0, max_length=10)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.beat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
