# Generated by Django 3.1.6 on 2021-03-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20210303_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='beat_thumbnails')),
                ('keywords', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
