# Generated by Django 3.1.6 on 2021-03-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_pagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelink',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Muss Querformat haben', null=True, upload_to='page-link_thumbnails'),
        ),
    ]
