# Generated by Django 3.1.6 on 2021-03-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20210313_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
