# Generated by Django 3.1.6 on 2021-03-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_contactrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='subject',
        ),
    ]
