# Generated by Django 3.1.6 on 2021-03-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20210313_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='content',
            field=models.CharField(default='empty', max_length=2000),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='email_address',
            field=models.CharField(default='empty', max_length=200),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='subject',
            field=models.CharField(default='empty', max_length=200),
        ),
    ]
