# Generated by Django 3.1.6 on 2021-03-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20210313_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagelink',
            name='keywords',
        ),
    ]
